# Generated by Django 5.0.3 on 2024-03-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_readerprofile_writterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerprofile',
            name='recent_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.blogmodel'),
        ),
        migrations.AlterField(
            model_name='writterprofile',
            name='recent_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.blogmodel'),
        ),
    ]
