# Generated by Django 5.0.3 on 2024-03-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_readerprofile_recent_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerprofile',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/profile_pic'),
        ),
        migrations.AddField(
            model_name='writterprofile',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/profile_pic'),
        ),
    ]
